import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

// Integrity guard for the committed feed fixture (src/app/FakeData/listy-injection.json).
// The fixture is generated by scripts/convert-live-demo-data.mjs from CrossWeave's
// multi-source live-demo corpus. The converter self-validates at generation time; this suite re-checks
// the COMMITTED artifact so a bad regen can't land silently.
//
// History: this file previously validated a hand-engineered reply-highlight demo
// (a synthetic post-processor). That layer was retired once the crossweave corpus
// gained ANNOTATED descendants (prepared_data_with_descendants): real reply threads
// now carry real NLP relations + nesting, emitted directly by convert-demo-data.mjs.
// These tests validate that real data.

const here = dirname(fileURLToPath(import.meta.url));
const data = JSON.parse(readFileSync(join(here, '../../src/app/FakeData/listy-injection.json'), 'utf8'));

const CATEGORIES = new Set([
  'agree', 'disagree', 'predictions', 'evidence_public', 'evidence_personal',
  'connections', 'questions', 'humor', 'values', 'framing', 'proposals', 'pointers', 'uncategorized',
]);

const validRange = (s, e, len) => Number.isInteger(s) && Number.isInteger(e) && s >= 0 && s < e && e <= len;

test('fixture is a non-empty array of entries', () => {
  assert.ok(Array.isArray(data) && data.length > 0, 'entries present');
});

test('live-demo timeline roots and quote tweets retain their corpus semantics', () => {
  const timeline = data.filter((entry) => entry.timelineRoot !== false);
  const quotes = timeline.filter((entry) => entry.focusPost.quotedPost);
  assert.equal(timeline.length, 21, 'six article/OP roots plus fifteen lifted quote roots');
  assert.equal(quotes.length, 15, 'all lifted quote-tweet roots are represented');
  for (const entry of quotes) {
    assert.ok(entry.focusPost.quotedPost.id, `quote ${entry.focusPost.id} has an embedded id`);
    assert.ok(entry.focusPost.quotedPost.title, `quote ${entry.focusPost.id} has an embedded title`);
    assert.equal(
      entry.ancestors?.[0]?.id,
      entry.focusPost.quotedPost.id,
      `quote ${entry.focusPost.id} resolves its embedded article as outermost context`,
    );
  }
});

test('full-thread candidate spans are retained on the ancestor post that owns them', () => {
  const rootKey = 'cmv_ai_will_not_create_more_jobs_than_it_destroys.json::1rq02gl';
  const root = data.find((entry) => entry.focusPost.sourceKey === rootKey);
  assert.ok(root, 'CMV root entry exists');

  const expected = new Map([
    ['nyt_ai-work-force-training-job-losses.json::152113692', 'Worker Transition Policy'],
    ['nyt_ai-labor-unemployment.json::149393764', 'Consumer Demand Collapse'],
    ['nyt_ai-labor-unemployment.json::149403339', 'Net Employment Effects'],
    ['cmv_ai_will_not_create_more_jobs_than_it_destroys.json::oa1m4j0', 'Capitalism And Human Inclusion'],
    ['nyt_ai-labor-unemployment.json::149395639', 'Redistribution And UBI'],
    ['cmv_ai_will_not_create_more_jobs_than_it_destroys.json::o9p2q1j', 'Wealth Driven Job Creation'],
    ['cmv_ai_will_not_create_more_jobs_than_it_destroys.json::o9onlag', 'Post Work Society'],
    ['fox_americas-ai-boom-jobs-opportunity-not-excuse-universal-basic-income.json::8psDYJY_EfGE366tm9oP7g--', 'Temporary Buildout Employment'],
    ['fox_dems-sound-alarm-ai-job-apocalypse-labor-market-isnt-following-script.json::ImxEGpcPEfGvPdatTj9n5w--', 'Net Employment Effects'],
    ['cmv_ai_will_not_create_more_jobs_than_it_destroys.json::o9q4z2u', 'Net Employment Effects'],
    ['fox_americas-ai-boom-jobs-opportunity-not-excuse-universal-basic-income.json::YyD.IJZGEfGE_8OMe3QTTA--', 'Net Employment Effects'],
  ]);

  for (const [sideKey, topic] of expected) {
    const post = root.relatedPosts.find((candidate) => candidate.sourceKey === sideKey);
    assert.ok(post, `retained full-thread candidate ${sideKey}`);
    assert.ok(
      post.relations.some((relation) => relation.topic === topic),
      `${sideKey} retains its ${topic} judgment`,
    );
  }
});

test('every focus post has the required shape and a real like count', () => {
  for (const e of data) {
    const fp = e.focusPost;
    assert.ok(typeof fp.id === 'string' && fp.id.length > 0, 'focus id');
    assert.ok(typeof fp.plainText === 'string' && fp.plainText.length > 0, `focus ${fp.id} plainText`);
    assert.ok(fp.content.includes('<p>'), `focus ${fp.id} content is HTML`);
    assert.ok(fp.account && typeof fp.account.display_name === 'string' && fp.account.acct, `focus ${fp.id} account`);
    assert.ok(Number.isFinite(fp.favourites_count) && fp.favourites_count >= 0, `focus ${fp.id} favourites_count`);
    assert.ok(Number.isFinite(fp.replies_count) && fp.replies_count >= 0, `focus ${fp.id} replies_count`);
  }
});

test('at least some focus posts carry real (non-zero) like counts', () => {
  const withLikes = data.filter((e) => e.focusPost.favourites_count > 0);
  assert.ok(withLikes.length >= 1, `expected real like counts, got ${withLikes.length}`);
});

test('every related post has >=1 relation with in-range, category-valid offsets', () => {
  for (const e of data) {
    const focusPlain = e.focusPost.plainText;
    for (const rp of e.relatedPosts) {
      assert.ok(Array.isArray(rp.relations) && rp.relations.length >= 1, `related ${rp.id} needs >=1 relation`);
      assert.ok(CATEGORIES.has(rp.category), `related ${rp.id} primary category ${rp.category}`);
      assert.ok(typeof rp.content === 'string' && rp.content.length > 0, `related ${rp.id} content`);
      for (const [i, r] of rp.relations.entries()) {
        const label = `related ${rp.id}[${i}]`;
        assert.ok(CATEGORIES.has(r.category), `${label} category ${r.category}`);
        assert.ok(typeof r.topic === 'string', `${label} topic`);
        assert.ok(validRange(r.focusStart, r.focusEnd, focusPlain.length), `${label} focus span in range`);
        assert.ok(validRange(r.contentStart, r.contentEnd, rp.content.length), `${label} content span in range`);
        assert.ok(r.focusStart <= r.focusCommentStart && r.focusCommentStart < r.focusCommentEnd && r.focusCommentEnd <= r.focusEnd, `${label} focus comment nested`);
        assert.ok(r.contentStart <= r.contentCommentStart && r.contentCommentStart < r.contentCommentEnd && r.contentCommentEnd <= r.contentEnd, `${label} content comment nested`);
      }
    }
  }
});

test('the pointers category is wired through the fixture', () => {
  const seen = new Set();
  for (const e of data) for (const rp of e.relatedPosts) for (const r of rp.relations) seen.add(r.category);
  assert.ok(seen.has('pointers'), `expected a pointers relation; saw ${[...seen].sort().join(', ')}`);
});

test('real reply threads have valid shape, counts, and threading', () => {
  let totalReplies = 0;
  for (const e of data) {
    const validParents = new Set([e.focusPost.id, ...(e.replies ?? []).map((r) => r.id)]);
    for (const r of e.replies ?? []) {
      totalReplies++;
      assert.ok(typeof r.id === 'string' && r.id.length > 0, 'reply id');
      assert.ok(typeof r.content === 'string', `reply ${r.id} content`);
      assert.ok(r.account && r.account.display_name, `reply ${r.id} account`);
      assert.ok(Number.isFinite(r.favourites_count) && r.favourites_count >= 0, `reply ${r.id} favourites_count`);
      assert.ok(validParents.has(r.inReplyToId), `reply ${r.id} inReplyToId ${r.inReplyToId} resolves within entry`);
    }
  }
  assert.ok(totalReplies >= 1, 'at least one real reply thread present');
});

test('any reply that carries relations has in-range offsets (forward-compat guard)', () => {
  for (const e of data) {
    const focusPlain = e.focusPost.plainText;
    for (const reply of e.replies ?? []) {
      const plain = reply.plainText ?? reply.content;
      for (const [i, r] of (reply.relations ?? []).entries()) {
        const label = `reply ${reply.id}[${i}]`;
        assert.ok(CATEGORIES.has(r.category), `${label} category`);
        assert.ok(validRange(r.focusStart, r.focusEnd, focusPlain.length), `${label} focus span`);
        assert.ok(validRange(r.contentStart, r.contentEnd, plain.length), `${label} content span`);
      }
    }
  }
});
